File:
    type: entity
    table: file
    indexes:
        IDX_8C9F3610537A1329:
            columns:
                - message_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        file:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        message:
            targetEntity: Message
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                message_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
